version: '3'

services:
  db:
    image: mdillon/postgis
    environment:
      - POSTGRES_USER=miotuser
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=miot
  web:
    build: .
    env_file:
      - ./docker.env
    command: bash docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
