# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='featured_image',
            field=models.ImageField(upload_to='media/uploads/poi'),
        ),
        migrations.AlterField(
            model_name='template',
            name='featured_image',
            field=models.ImageField(upload_to='media/uploads/templates'),
        ),
    ]
